### ISSUE TITLE
Can not use sync function to connect to host

### ISSUE THREAD

**Issue by doggedvirus** [antlafarge/QtWebsocket#31]
When create a client to connect to host,if the client use sync function,the connection would not be created successfully.The code like below:
wsSocket->connectToHost(QString("ws://127.0.0.1"), port);
wsSocket->waitForConnected(3000);//Fail

**Comment by antlafarge** [comment]
Okay, I'm not sure waitForConnected was properly implemented. But I have not worked on this project for a long time. It is deprecated. If you can, I recommand you to use this official implementation from Qt : http://doc.qt.io/qt-5/qtwebsockets-index.html
Anyway if you find and fix this issue, feel free to share your patch using a pull request.
