### ISSUE TITLE
:-1: 错误:No rule to make target `../../QtWebsocket/libQtWebsocket.a', needed by `Client'.  Stop.

### ISSUE THREAD

**Issue by 0x706a79** [antlafarge/QtWebsocket#32]
:-1: 错误:No rule to make target `../../QtWebsocket/libQtWebsocket.a', needed by `Client'.  Stop.

**Comment by Stoptimerag** [comment]
win下编译首先把pro文件里面连接的.a改为.lib
然后把websocket pro文件 TARGET =  QtWebsocket改为 TARGET = libQtWebsocket
最后 先编译websocket。再编译其他。
