### ISSUE TITLE
ignoreSslErrors doesn't work

### ISSUE THREAD

**Issue by medadyoung** [antlafarge/QtWebsocket#33]
Hello,
I enable 
sslSocket->ignoreSslErrors() 
but connection is still dropped when this error occurs "The host name did not match any of the valid hosts for this certificate"

**Comment by me21** [comment]
Websockets have been included into Qt 5 long ago. Please use them, this repo is not maintained.

**Comment by antlafarge** [comment]
Yes this repo is deprecated. If you have any good reason to use this implementation (because of old version of Qt for example), and if you manage to fix this issue, feel free to do a pull request, and I will integrate it.
